name: Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint and typecheck the project
        run: yarn verify
      - name: Build the plugin
        run: yarn build
